
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package yu.ac.ns.ftn.informatika.ws.bezbjednost;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;

import model.mbp.MedjubankarskiPrenosi;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2017-06-15T14:17:39.856+02:00
 * Generated source version: 2.6.5
 * 
 */
public class BezbjednostClient {

    public static void main(String[] args) throws Exception {
//        QName serviceName = new QName("http://informatika.ftn.ns.ac.yu/ws/bezbjednost", "BezbjednostService");
//        QName portName = new QName("http://informatika.ftn.ns.ac.yu/ws/bezbjednost", "BezbjednostPort");
//
//        Service service = Service.create(serviceName);
//        service.addPort(portName, SOAPBinding.SOAP11HTTP_BINDING,
//                        "http://localhost:9090/BezbjednostPort"); 
//        yu.ac.ns.ftn.informatika.ws.bezbjednost.Bezbjednost client = service.getPort(portName,  yu.ac.ns.ftn.informatika.ws.bezbjednost.Bezbjednost.class);
        // Insert code to invoke methods on the client here
    	try {
			//kreiranje web servisa
			URL wsdlLocation = new URL("http://localhost:8080/poslovnaBanka/services/Bezbjednost?wsdl");
			QName serviceName = new QName("http://informatika.ftn.ns.ac.yu/ws/bezbjednost", "BezbjednostService");
			QName portName = new QName("http://informatika.ftn.ns.ac.yu/ws/bezbjednost", "BezbjednostPort");

			Service service = Service.create(wsdlLocation, serviceName);
			
			Bezbjednost hello = service.getPort(portName, Bezbjednost.class); 
			
			//poziv web servisa
			
			String response = hello.sayHi("ovo je dokument sad hihi");
			System.out.println("Response from WS: " + response);
			
			
			
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
    }

}