
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package yu.ac.ns.ftn.informatika.ws.mbp;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.Marshaller;
import javax.xml.namespace.QName;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;

import org.w3c.dom.Document;

import model.mbp.MedjubankarskiPrenosi;
import yu.ac.ns.ftn.informatika.ws.hello.Hello;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2017-06-14T01:04:24.695+02:00
 * Generated source version: 2.6.5
 * 
 */
public class MBPClient {

    public static void main(String[] args) throws Exception {
//        QName serviceName = new QName("http://informatika.ftn.ns.ac.yu/ws/mbp", "MBPService");
//        QName portName = new QName("http://informatika.ftn.ns.ac.yu/ws/mbp", "MBPPort");
//
//        Service service = Service.create(serviceName);
//        service.addPort(portName, SOAPBinding.SOAP11HTTP_BINDING,
//                        "http://localhost:9090/MBPPort"); 
//        yu.ac.ns.ftn.informatika.ws.mbp.MBP client = service.getPort(portName,  yu.ac.ns.ftn.informatika.ws.mbp.MBP.class);
        
        // Insert code to invoke methods on the client here
    	try {
			//kreiranje web servisa
			URL wsdlLocation = new URL("http://localhost:8080/poslovnaBanka/services/MBP?wsdl");
			QName serviceName = new QName("http://informatika.ftn.ns.ac.yu/ws/mbp", "MBPService");
	        QName portName = new QName("http://informatika.ftn.ns.ac.yu/ws/mbp", "MBPPort");

			Service service = Service.create(wsdlLocation, serviceName);
			
			MBP hello = service.getPort(portName, MBP.class); 
			
			//poziv web servisa
			MedjubankarskiPrenosi medjBanPrenosi = new MedjubankarskiPrenosi();
			String response = hello.doMbp(medjBanPrenosi);
			System.out.println("Response from WS: " + response);
			
			
			
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
    }

}