
package yu.ac.ns.ftn.informatika.ws.mbp;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2017-06-14T01:04:24.680+02:00
 * Generated source version: 2.6.5
 * 
 */
 
public class MBPServer{

    protected MBPServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new yu.ac.ns.ftn.informatika.ws.mbp.MBPImpl();
        String address = "http://localhost:9090/MBPPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new MBPServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 